language: node_js
node_js:
  - '8'
  - '9'
cache: yarn
before_install:
  - yarn globa add lerna
before_script:
  - lerna bootstrap
script:
  - lerna run test:coverage --scope ringcentral-widgets-test --stream
  - lerna run test --scope ringcentral-integration --stream
after_success:
   - cat packages/ringcentral-widgets/coverage/lcov.info | ./node_modules/.bin/coveralls

jobs:
  include:
    - stage: commons npm release
      node_js: "8"
      script: ./scripts/commons_prepare_release.sh
      before_deploy:
        - cd release/ringcentral-integration
      after_deploy:
        - cd ../../
      deploy:
        - provider: script
          skip_cleanup: true
          script: echo "Script1:" && pwd
        - provider: script
          skip_cleanup: true
          script: echo "Script2:" && pwd
    - stage: widgets npm release
      node_js: "8"
      script: ./scripts/widgets_prepare_release.sh
      before_deploy:
        - cd release/ringcentral-widgets
      after_deploy:
        - cd ../../
      deploy:
        - provider: script
        skip_cleanup: true
        script: echo "deploy1:" && pwd
        - provider: script
          skip_cleanup: true
          script: echo "deploy2:" && pwd
    - stage: widgets script release
      node_js: "8"
      script: ./scripts/widgets_prepare_release.sh
      before_deploy:
        - cd release/ringcentral-widgets
      after_deploy:
        - cd ../../
      deploy:
        provider: script
        skip_cleanup: true
        script: echo "deploy2:" && pwd
    - stage: widgets docs build
      node_js: "8"
      before_deploy:
        - lerna run --scope ringcentral-widgets-docs build --stream
      deploy:
        provider: script
        skip_cleanup: true
        script: cd packages/ringcentral-widgets-docs/gh-pages && pwd
