language: node_js
node_js:
  - '5'
  - '6'
# after_success:
#    - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
before_deploy:
  - ./scripts/prepare_release.sh && cd release
deploy:
  - provider: npm
    email: embbnux@embbnux.com
    skip_cleanup: true
    api_key:
      secure: dEV+cBhn75/3ryLfLl4sVpuNIcl4nikmM2NqlbpODESznUFcVAHtcEWNMx/KShrgnl4AxoClAB459/WSCGqGy5jzQ7VlVbYU1mkPw17lQY7mpBIoR7Gm9Igsvk0Bx8jO3AINS+wsDi24vhv7zOGt1s1b0itUR2V8KCVKeMpionslTnkI2U3VgpCoVG5yA1sisMwiBX2fHzehwk7R84Q8dsc3xnQfMyE+nZiqud4CJOYsl/gsKEVyjzURK7v5zlroV+k6gV3w884G4LaFHZOup41+q5+zK1bN0y2X84BUDBRlMs4GxAMNm1SXJk/4TQRjgArRC8UsjyEeC+wEnNNjBtXPtt5Qy6EnNVZe6Wtw63C2BjpHZ4qI5u0wBgGPAcnWq3ZGvd48varFkIc+GtFh/7urpByPpRfoF3D6UvscPEd6WpHXdscfggoiIVyAMN55Mhb9qkOcgjatiZZg7QIJdlzyIazSBUm7bvyU3zsDMzIG/cighwRehm7+X2A/7NCUTOWnkGk8A76RZllWB4gx+bb0KeKUC0xBrQVwj7xkLw7l0fkEy8NrlEkShsGZGR1Dc86YtgWFO0m9Aa17u7PcLvnPyb5vPwNR/xsKEdOQwEe2t+qlI+abju5v5FIXmmRnHGZS3WpIjbVbJ021LOGYCsFVt03MppS9nR8ZoRLsHEs=
    on:
      node: '6'
      tags: true
      condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+"
      repo: ringcentral/ringcentral-js-widget
  - provider: pages
    skip_cleanup: true
    github_token: $RELEASE_TOKEN
    local_dir: ../docs/gh-pages
    email: 'integrations@ringcentral.com'
    name: 'RingCentral Integrations Team'
    on:
      node: '6'
      tags: true
      condition: "$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+"
      repo: ringcentral/ringcentral-js-widget
